import { guessType, parseTypes } from "./types";
//import generatePython from "./python/generator";

export default async function generate(
  outputLanguage: string,
  json: string,
  inline: boolean
): Promise<string> {
  // URL
  if (json.startsWith("http")) {
    json = await (await fetch(json)).text();
  }

  const jsonObject = JSON.parse(json);
  const types = parseTypes(jsonObject, "AutoGenerated");

  if (outputLanguage === "python") {
    return JSON.stringify(types);
    //return generatePython(schema);
  } else {
    throw Error(`Unable to generate language ${outputLanguage}`);
  }
}
