const input = document.getElementById("input");
const output = document.getElementById("output");
const flatten = document.getElementById("flatten");
let json = input.value;

function updoot() {
  output.value = jsonToPython(
    input.value,
    "AutoGenerated",
    !inline.checked
  ).python;
}

input.addEventListener("change", updoot);
inline.addEventListener("change", updoot);
updoot();
